url.get.user=https://jsonplaceholder.typicode.com/users?username=%s
url.get.posts=https://jsonplaceholder.typicode.com/users/%s/posts
url.get.comments=https://jsonplaceholder.typicode.com/posts/%s/comments
regex.email=^(?=.{1,64}@)[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@[^-][A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$