version: 2

orbs:
  maven: circleci/maven@1.1.0

jobs:
  test:
    steps:
      - checkout
      - run: mvn test
      - store_artifacts:
          path: target
    docker:
      - image: circleci/openjdk:8u171-jdk

workflows:
  maven_test:
    jobs:
      - maven/test
